//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3603.
// 
namespace KoctasMobil.WS_Sayim {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZKTMOBIL_SAYIM", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class service : System.Web.Services.Protocols.SoapHttpClientProtocol {

        protected override System.Net.WebRequest GetWebRequest(Uri uri)
        {
            System.Net.HttpWebRequest request = (System.Net.HttpWebRequest)base.GetWebRequest(uri);
            request.KeepAlive = false;
            request.ProtocolVersion = System.Net.HttpVersion.Version10;
            return request;
        }

        /// <remarks/>
        public service() {
            this.Url = "http://ktqa.koctas.com.tr:8000/sap/bc/srt/rfc/sap/zktmobil_sayim/500/zktmobil_say" +
                "im/zktmobil_sayim";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZktmobilCheckAdrResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZktmobilCheckAdrResponse ZktmobilCheckAdr([System.Xml.Serialization.XmlElementAttribute("ZktmobilCheckAdr", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZktmobilCheckAdr ZktmobilCheckAdr1) {
            object[] results = this.Invoke("ZktmobilCheckAdr", new object[] {
                        ZktmobilCheckAdr1});
            return ((ZktmobilCheckAdrResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginZktmobilCheckAdr(ZktmobilCheckAdr ZktmobilCheckAdr1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ZktmobilCheckAdr", new object[] {
                        ZktmobilCheckAdr1}, callback, asyncState);
        }
        
        /// <remarks/>
        public ZktmobilCheckAdrResponse EndZktmobilCheckAdr(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ZktmobilCheckAdrResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZktmobilSayimSaveResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZktmobilSayimSaveResponse ZktmobilSayimSave([System.Xml.Serialization.XmlElementAttribute("ZktmobilSayimSave", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZktmobilSayimSave ZktmobilSayimSave1) {
            object[] results = this.Invoke("ZktmobilSayimSave", new object[] {
                        ZktmobilSayimSave1});
            return ((ZktmobilSayimSaveResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginZktmobilSayimSave(ZktmobilSayimSave ZktmobilSayimSave1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ZktmobilSayimSave", new object[] {
                        ZktmobilSayimSave1}, callback, asyncState);
        }
        
        /// <remarks/>
        public ZktmobilSayimSaveResponse EndZktmobilSayimSave(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ZktmobilSayimSaveResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZktmobilCheckAdr {
        
        private string iAddressField;
        
        private string iTypeField;
        
        private ZkmobilReturn[] teReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IAddress {
            get {
                return this.iAddressField;
            }
            set {
                this.iAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IType {
            get {
                return this.iTypeField;
            }
            set {
                this.iTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZkmobilReturn[] TeReturn {
            get {
                return this.teReturnField;
            }
            set {
                this.teReturnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkmobilReturn {
        
        private string rcCodeField;
        
        private string rcTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RcCode {
            get {
                return this.rcCodeField;
            }
            set {
                this.rcCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RcText {
            get {
                return this.rcTextField;
            }
            set {
                this.rcTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZkmobilItems {
        
        private string iblnrField;
        
        private string rafField;
        
        private string matnrField;
        
        private decimal miktarField;
        
        private string ean11Field;
        
        private string meinsField;
        
        private string personelField;
        
        private string tarihField;
        
        private string saatField;
        
        private string statuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Iblnr {
            get {
                return this.iblnrField;
            }
            set {
                this.iblnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Raf {
            get {
                return this.rafField;
            }
            set {
                this.rafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Miktar {
            get {
                return this.miktarField;
            }
            set {
                this.miktarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ean11 {
            get {
                return this.ean11Field;
            }
            set {
                this.ean11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Meins {
            get {
                return this.meinsField;
            }
            set {
                this.meinsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Personel {
            get {
                return this.personelField;
            }
            set {
                this.personelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Saat {
            get {
                return this.saatField;
            }
            set {
                this.saatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Statu {
            get {
                return this.statuField;
            }
            set {
                this.statuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZktmobilCheckAdrResponse {
        
        private string eDocumentField;
        
        private ZkmobilReturn[] teReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EDocument {
            get {
                return this.eDocumentField;
            }
            set {
                this.eDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZkmobilReturn[] TeReturn {
            get {
                return this.teReturnField;
            }
            set {
                this.teReturnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZktmobilSayimSave {
        
        private ZkmobilItems[] itItemsField;
        
        private ZkmobilReturn[] teReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZkmobilItems[] ItItems {
            get {
                return this.itItemsField;
            }
            set {
                this.itItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZkmobilReturn[] TeReturn {
            get {
                return this.teReturnField;
            }
            set {
                this.teReturnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZktmobilSayimSaveResponse {
        
        private ZkmobilItems[] itItemsField;
        
        private ZkmobilReturn[] teReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZkmobilItems[] ItItems {
            get {
                return this.itItemsField;
            }
            set {
                this.itItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZkmobilReturn[] TeReturn {
            get {
                return this.teReturnField;
            }
            set {
                this.teReturnField = value;
            }
        }
    }
}
